# Generated by Django 3.1.7 on 2021-03-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210312_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_email_active',
            field=models.BooleanField(default=True),
        ),
    ]
