# Generated by Django 3.1.7 on 2021-03-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_staff_is_email_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='password',
            new_name='passwrd',
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_email', models.CharField(max_length=100)),
                ('app_password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.staff')),
            ],
        ),
    ]
