# Generated by Django 3.1.7 on 2021-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210314_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_email_active',
            field=models.BooleanField(default=False),
        ),
    ]
