# Generated by Django 3.1.7 on 2021-03-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210314_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
